control_points:
- carla:
    x: 0.0
    y: 0.0
    z: 0.0
  traffic:
    x: 0.0
    y: 0.0
    z: 0.0
- carla:
    x: 100.0
    y: 0.0
    z: 0.0
  traffic:
    x: 100.0
    y: 0.0
    z: 0.0
- carla:
    x: 0.0
    y: -100.0
    z: 0.0
  traffic:
    x: 0.0
    y: 100.0
    z: 0.0
schema_version: '1.0'
source_coordinate_system: OpenDRIVE
target_coordinate_system: CARLA
transform:
  axis_matrix:
  - - 1.0
    - 0.0
  - - 0.0
    - -1.0
  heading_offset_rad: 0.0
  heading_sign: -1
  translation_m:
    x: 0.0
    y: 0.0
    z: 0.0
